% Stim_cal_load
% Generates calibration curve for stimulation pulse for scousetom system 
% PulseVoltage.txt generated by Stim_cal.vi - recorded as
% PulseOutCalibrate.ino runs on the arduino 

%% read that business

in=dlmread('../labview/PulseVoltage.txt');

%% reshape based on repeats

R_set=unique(in(:,1)); %number of potentiometer settings used
R_set_num=length(R_set);
R_rep=size(in,1)/R_set_num;

%find mean and standard dev
Vpulseraw=reshape(in(:,2),R_set_num,R_rep);
Vrefraw=reshape(in(:,3),R_set_num,R_rep);

Vpulse=nanmean(Vpulseraw,2);
Vpulsestd=nanstd(Vpulseraw,0,2);
%%
figure
% [hl,hp]=boundedline(R_set,Vpulse,Vpulsestd);
plot(R_set,Vpulse,'o-');
xlabel('Wiper Pot setting')
ylabel('Pulse Voltage');
title('All settings tested');



%% take only settings of interest

minv=0.5; % in theory below 3.3V would be weird as below logic level on MOSFET
maxv=11; % 12 V should be max based on 12V regulator

R=R_set(Vpulse < maxv & Vpulse > minv);
Vp=Vpulse(Vpulse < maxv & Vpulse > minv);

figure
% [hl,hp]=boundedline(R_set,Vpulse,Vpulsestd);
plot(R,Vp,'o-');
xlabel('Wiper Pot setting')
ylabel('Pulse Voltage V');
title('settings of interest');


%% save for use in arduino control software

datemade=date;

fid=fopen('VstimCal.txt','w+');

fprintf(fid,'##################################\n');
fprintf(fid,'#ScouseTom Pulse Voltage Settings\n');
fprintf(fid,'#Date and time this file was created : %s\n',datestr(clock));
fprintf(fid,'#The PC name was : %s\n',getenv('COMPUTERNAME')); %only works on windows
fprintf(fid,'#The Username was : %s\n',getenv('USERNAME'));
fprintf(fid,'#WiperSetting\tStimVoltage\r\n');
for iline=1:length(Vp)
    fprintf(fid,'%d\t%.2f\r\n',R(iline),Vp(iline));
end

fclose(fid);

% dlmwrite('VstimCal.txt',[R Vp],'delimiter','\t','precision','%.3f');
save('VstimCal','R','Vp','datemade');




